# Generated by Django 4.1.2 on 2022-11-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cathegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('producer', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=200)),
                ('issue_year', models.CharField(max_length=10)),
                ('min_age_of_player', models.PositiveSmallIntegerField()),
                ('min_number_of_players', models.PositiveSmallIntegerField()),
                ('max_number_of_players', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('how_to_play', models.TextField(max_length=2000, null=True)),
                ('cathegory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boardgame', to='boardgames.cathegory')),
            ],
        ),
    ]
