# Generated by Django 4.1.2 on 2022-11-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardgameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='boardgames/%Y/%m/%d')),
                ('boardgames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardgames.boardgame')),
            ],
        ),
    ]
