# Generated by Django 4.1.2 on 2022-11-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='how_to_play',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
