# Generated by Django 4.1.2 on 2022-11-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_boardgameimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgameimage',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
