# Generated by Django 4.1.2 on 2022-11-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_boardgame_how_to_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='how_to_play',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
