# Generated by Django 4.1.2 on 2022-11-12 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_alter_boardgameimage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgameimage',
            name='boardgames',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardimg', to='boardgames.boardgame'),
        ),
    ]
