# Generated by Django 4.1.2 on 2022-11-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_alter_boardgame_how_to_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathegory',
            name='description',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
